### ISSUE TITLE
Init error at line 570

### ISSUE THREAD

**Issue by bitskc** [vishalbalaji/firebox#1]
When running firebox init I get the following errors:
```
: line 570: syntax error near unexpected token `('
: line 570: `		diff -a --color -yE --strip-trailing-cr <(echo "$existing_bookmarks" | sed 's/<|firebox:sep|>/ => /g') <(echo "$new_bookmarks" | sed 's/<|firebox:sep|>/ => /g')'
```

This is on MacOS 13.0.1

**Comment by vishalbalaji** [comment]
Hey, thanks for the issue! I wrote this script mainly as a utility on Linux in a very scrappy way and it's not really optimised to run on other platforms.

The issue you mentioned here can be solved with an easy fix, but there are a lot of other issues with it that prevent it from working on Mac OS in its current state and needs major re-writes.

I only recently started using a Mac for work and I plan on working on this if I get some free time. In the meantime, I am happy to accept any pull requests :smile:.

**Comment by bitskc** [comment]
Ok, thanks for the info.  I love the idea.  It's exactly what I've been looking for.  Great work!  Maybe I'll install it in one of my Linux builds and see how it works in there.  Unfortunately, I don't think I'll be of much help getting this working on Mac, but maybe I'll see what I can do...  Thanks!

**Comment by bitskc** [comment]
Would you be able to point me in the right direction with the fix for that particular issue?

**Comment by vishalbalaji** [comment]
I am glad to hear that this might be helpful for you! I just pushed up a fix for this in the most recent commit, you can refer to the diff there.

Basically, I was just using some weird POSIX specific syntax that Mac OS didn't like, which I had to resolve in a roundabout way by using temp files.

Like I said earlier, this still won't really work well because there are a few other things that are Linux specific in there.

**Comment by bitskc** [comment]
[like]  Andy Hayes reacted to your message:
________________________________
